---

scala_version: "2.10.3"
sumo_version: "19.99-5"

apt_packages:
    - curl
    - dhcpcd
    - dnsutils
    - git
    - host
    - iptraf
    - joe
    - less
    - libpcap0.8
    - libpcre3
    - libprotobuf-c0
    - lsof
    - mc
    - mdadm
    - ntp
    - openjdk-7-jre-headless
    - openjdk-7-jdk
    - openssh-server
    - parted
    - pigz
    - psmisc
    - resolvconf
    - strace
    - sudo
    - vim
    - unzip
    - zip
