---
- hosts: chroot
  user: root

  tasks:

    - name: Installing apt packages
      apt: pkg={{ item }} update_cache=yes
      with_items: apt_packages

    - name: Downloading SumoLogic Collector
      get_url: url=http://files.celtra.com.s3.amazonaws.com/sumologic/sumocollector_19.99-5_amd64.deb
                dest=/tmp/sumocollector_19.99-5_amd64.deb mode=0440

    - name: Installing SumoLogic Collector
      command: dpkg -i /tmp/sumocollector_19.99-5_amd64.deb

    - name: Downloading collectd
      get_url: url='http://files.celtra.com.s3.amazonaws.com/debian/wheezy/collectd_5.4.1-celtra-7_amd64.deb' dest=/tmp/collectd_5.4.1-celtra-7_amd64.deb

    - name: Installing collectd
      command: dpkg --force-confold -i /tmp/collectd_5.4.1-celtra-7_amd64.deb

    - name: Downloading Spark
      get_url: url='http://files.celtra.com/spark/spark-1.1.0-bin-hadoop2.4-httpclient4.2.tgz' dest='/tmp/spark-1.1.0-bin-hadoop2.4-httpclient4.2.tgz'

    - name: Unpacking Spark
      shell: mkdir /opt/spark && tar -C /opt/spark --strip-components=1 -xzf /tmp/spark-1.1.0-bin-hadoop2.4-httpclient4.2.tgz

    - name: Configuring Spark Logging
      command: mv /opt/spark/conf/log4j.properties.template /opt/spark/conf/log4j.properties

    - name: Downloading Scala
      get_url: url=http://www.scala-lang.org/files/archive/scala-{{ scala_version }}.tgz
                dest=/tmp/scala-{{ scala_version }}.tgz

    - name: Untaring Scala
      shell: cd /opt && tar xzf /tmp/scala-{{ scala_version }}.tgz

    - name: Symlinking Scala
      file: src=/opt/scala-{{ scala_version }} dest=/opt/scala state=link

    - name: Enabling Services
      service: name={{ item }} enabled=yes
      with_items: [ 'spark', 'collector', 'collectd' ]
