#!/bin/bash
set -eu -o pipefail

APP_ROOT=$(dirname $(dirname $(readlink -e $0)))

cd "$APP_ROOT/ami/root"
find ./ -exec sh -c "if [ -f '{}' ]; then cat '{}'; else echo '{}'; fi" \; | md5sum | cut -d' ' -f1
