#!/bin/bash
### BEGIN INIT INFO
# Provides:          firstboot-setup
# Required-Start:    $local_fs $network rsyslog
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# X-Interactive:     true
# Short-Description: One-time app setup on first boot.
### END INIT INFO

set -eu -o pipefail

curl --retry 3 --silent --show-error --fail --output /etc/user-data http://169.254.169.254/2008-02-01/user-data

source /etc/user-data

# Add colored prompt to root's .profile
COLOR=${PROMPT_COLOR}
if [ -n "$COLOR" ]
then
    echo '
# Colorize prompt
RESET="\033[0m"
BOLD="\033[1m"
declare -A colors=(["black"]="\033[30m" ["red"]="\033[31m" ["green"]="\033[32m" ["yellow"]="\033[33m" ["blue"]="\033[34m" ["magenta"]="\033[35m" ["cyan"]="\033[36m" ["white"]="\033[37m")
PS1="\[${colors['$COLOR']}\]\u@\h:\w\[$BOLD\]\\\$\[$RESET\] "
' >>/root/.profile
fi

INSTANCE_ID=$(wget -q -O - http://instance-data.ec2.internal/latest/meta-data/instance-id)
# Fix SumoConfig
for var in $(cat /opt/SumoCollector/config/wrapper.conf |  grep -Po '\$\$([^\$]*)\$\$*' | tr -d '$')
do
    key=${var//$/\\$}
    key=${key//\[/\\[}
    key=${key//\]/\\]}
    sed -i /opt/SumoCollector/config/wrapper.conf -e 's|\$\$'${key}'\$\$|'"${!var}"'|g'
done
chown sumo:sumo /opt/SumoCollector/config/wrapper.conf
chmod 644 /opt/SumoCollector/config/wrapper.conf

# Prevent script from running again
insserv --remove firstboot-setup
