#!/bin/bash
#
# Usage: prefix <prefix> <command> [arg...]
#
# Runs command <comand>, prefixing it's stdout and stderr with <prefix>.
#
# By Jaka Jancar <jaka@kubje.org>
#
set -e

PREFIX=$1
shift

prefix_stream () {
    while read LINE; do echo "$PREFIX$LINE"; done
}

{ "$@" 2>&1 1>&3 | prefix_stream 1>&2; exit ${PIPESTATUS[0]}; } 3>&1 | prefix_stream; exit ${PIPESTATUS[0]}