#!/usr/bin/env python

import sys
import json

config = json.loads(sys.argv[1])
facts = json.loads(sys.argv[2])

print "Stack name:", config['stack_name']
print "Using AMI:", config['ami']

for instance in facts.keys():

    print " "
    print "System resources:"
    print " Total swap:", facts[instance]['ansible_facts']['ansible_swaptotal_mb'], "MB"
    print " Free swap:", facts[instance]['ansible_facts']['ansible_swapfree_mb'], "MB"
    print " "
    print " Total memory:", facts[instance]['ansible_facts']['ansible_memtotal_mb'], "MB"
    print " Free memory:", facts[instance]['ansible_facts']['ansible_memfree_mb'], "MB"
    print " "