#!/bin/bash
### BEGIN INIT INFO
# Provides:          firstboot-setup
# Required-Start:    $local_fs $network rsyslog
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# X-Interactive:     true
# Short-Description: One-time app setup on first boot.
### END INIT INFO

set -eu -o pipefail

curl --retry 3 --silent --show-error --fail --output /etc/user-data http://169.254.169.254/2008-02-01/user-data

source /etc/user-data

# Add colored prompt to root's .profile
COLOR=${PROMPT_COLOR}
if [ -n "$COLOR" ]
then
    echo '
# Colorize prompt
RESET="\033[0m"
BOLD="\033[1m"
declare -A colors=(["black"]="\033[30m" ["red"]="\033[31m" ["green"]="\033[32m" ["yellow"]="\033[33m" ["blue"]="\033[34m" ["magenta"]="\033[35m" ["cyan"]="\033[36m" ["white"]="\033[37m")
PS1="\[${colors['$COLOR']}\]\u@\h:\w\[$BOLD\]\\\$\[$RESET\] "
' >>/root/.profile
fi

## tmp RAID0 setup
echo "Setting up RAID0"
declare -a DEVICES=( $(find /dev -maxdepth 1 -regex '.*xvd[bcde]') )
for device in "${DEVICES[@]}"
do
    echo "  - Creating RAID partition on $device"
    parted -s $device rm 1 || true
    parted -s $device mklabel msdos
    parted -s -a optimal $device unit % mkpart primary 0% 100%
    parted -s $device set 1 raid on
done
echo "  - Creating RAID0 /dev/md0 device"
declare -a DEVICES=( $(find /dev -maxdepth 1 -regex '.*xvd[bcde]1') )
mdadm --create /dev/md0 --force --raid-devices=${#DEVICES[@]} --level=raid0 ${DEVICES[@]}
echo "DEVICE ${DEVICES}" > /etc/mdadm/mdadm.conf
echo "CREATE owner=root group=disk mode=0600 auto=yes" >> /etc/mdadm/mdadm.conf
echo "HOMEHOST <system>" >> /etc/mdadm/mdadm.conf
echo "MAILADDR root" >> /etc/mdadm/mdadm.conf
# Have to wait here a bit or shit wont work
sleep 5
mdadm --detail --scan >> /etc/mdadm/mdadm.conf
echo "  - Creating EXT4 filesystem"
mkfs.ext4 -q -m 0 -O ^has_journal -O dir_index /dev/md0
echo "  - Mounting /dev/md0 to /tmp"
echo "/dev/md0   /tmp  ext4    noatime,nodiratime,noacl,nouser_xattr,data=writeback,barrier=0,nobh 0 0" >> /etc/fstab
mount /tmp

INSTANCE_ID=$(wget -q -O - http://instance-data.ec2.internal/latest/meta-data/instance-id)
# Fix SumoConfig
for var in $(cat /opt/SumoCollector/config/wrapper.conf |  grep -Po '\$\$([^\$]*)\$\$*' | tr -d '$')
do
    key=${var//$/\\$}
    key=${key//\[/\\[}
    key=${key//\]/\\]}
    sed -i /opt/SumoCollector/config/wrapper.conf -e 's|\$\$'${key}'\$\$|'"${!var}"'|g'
done
chown sumo:sumo /opt/SumoCollector/config/wrapper.conf
chmod 644 /opt/SumoCollector/config/wrapper.conf

# Prevent script from running again
insserv --remove firstboot-setup
