#!/bin/bash
### BEGIN INIT INFO
# Provides:          firstboot-setup
# Required-Start:    $local_fs $network rsyslog
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# X-Interactive:     true
# Short-Description: One-time app setup on first boot.
### END INIT INFO

set -eu -o pipefail

curl --retry 3 --silent --show-error --fail --output /etc/user-data http://169.254.169.254/2008-02-01/user-data

source /etc/user-data

# Add colored prompt to root's .profile
COLOR=${PROMPT_COLOR}
if [ -n "$COLOR" ]
then
    echo '
# Colorize prompt
RESET="\033[0m"
BOLD="\033[1m"
declare -A colors=(["black"]="\033[30m" ["red"]="\033[31m" ["green"]="\033[32m" ["yellow"]="\033[33m" ["blue"]="\033[34m" ["magenta"]="\033[35m" ["cyan"]="\033[36m" ["white"]="\033[37m")
PS1="\[${colors['$COLOR']}\]\u@\h:\w\[$BOLD\]\\\$\[$RESET\] "
' >>/root/.profile
fi

## tmp RAID0 setup
echo "Mounting temp disks"
declare -a DEVICES=( $(find /dev -maxdepth 1 -regex '.*xvd[bcde]') )
for device in "${DEVICES[@]}"
do
	tmp_dir=/tmp/spark-${device/\/dev\//}
	mkdir $tmp_dir
	mkfs.ext4 -q -m 0 -O ^has_journal -O dir_index $device
	echo "$device   $tmp_dir  ext4    noatime,nodiratime,noacl,nouser_xattr,data=writeback,barrier=0,nobh 0 0" >> /etc/fstab
	mount $tmp_dir
done

# Configure SumoLogic Collector
cat <<EOF > /etc/sumo.conf
name=${CLUSTER_NAME}-${SERVER_ROLE}-$(curl --silent --retry 3 --show-error http://169.254.169.254/2012-01-12/meta-data/instance-id)
email=${SUMO_USERNAME}
password=${SUMO_PASSWORD}
sources=/etc/sumo.sources
EOF

# Sed reorders test.celtra.com to com.celtra.test
METRICS_PREFIX="$(echo ${METRICS_PREFIX}.stacks.${CLUSTER_NAME}.${SERVER_ROLE}.${HOSTNAME} | sed -e :a -e 's/\([^\.]*\)\.\([^\.]*\)/\2_\1/;ta;s/_/./g')"
cat /etc/collectd.conf.example  | \
  sed -e "s/<METRICS_PREFIX>/${METRICS_PREFIX}/" \
      -e "s/<METRICS_ENDPOINT>/${METRICS_ENDPOINT}/" > /etc/collectd.conf

# Prevent script from running again
insserv --remove firstboot-setup
